name: OpenSSF Scorecard

on:
  push:
    branches:
      - main  # You can change the branch name if needed
  pull_request:
    branches:
      - main  # This ensures the scorecard runs on pull requests as well

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Download and install OpenSSF Scorecard
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/ossf/scorecard/releases/latest" | jq -r .tag_name)
          echo "Latest version: $VERSION"
          DOWNLOAD_URL="https://github.com/ossf/scorecard/releases/download/$VERSION/scorecard-linux-amd64-$VERSION.tar.gz"
          curl -LO $DOWNLOAD_URL
          tar -xvf "scorecard-linux-amd64-$VERSION.tar.gz"
          chmod +x scorecard
          sudo mv scorecard /usr/local/bin/

      - name: Run OpenSSF Scorecard
        run: |
          scorecard https://github.com/${{ github.repository }}
