name: OpenSSF Scorecard

on:
  push:
    branches:
      - main  # You can change the branch name if needed
  pull_request:
    branches:
      - main  # This ensures the scorecard runs on pull requests as well

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  # You can adjust the version of Go as needed

      - name: Install OpenSSF Scorecard
        run: |
          go install github.com/ossf/scorecard/cmd/scorecard@latest

      - name: Run OpenSSF Scorecard
        run: |
          scorecard https://github.com/${{ github.repository }}
